### PR TITLE
add the loader scripts to the correct place for apps

### PR DESCRIPTION
**Pull request by Links2004**

### CODE REVIEW

**Comment by HaNdTriX** [comment]
Thanks for your PR! 

Nevertheless I am not sure I we should support the deprecated chrome apps 🤔.
I recommend switching to electron instead.

These apps won't be usable in the near future. 

https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

> ### Update on December 5, 2017:
> Chrome Apps will be removed from Chrome Web Store search & browse functions in mid-December 2017. Existing apps will continue to work and receive updates.
 The Chrome browser will continue to load packaged and hosted apps on Windows, Mac, and Linux beyond the previously announced deprecation timeline. Another update will be posted here when a new date for the Chrome Apps EOL on Windows, Mac, and Linux has been finalized.

**Comment by HaNdTriX** [comment]
> Important: Chrome will be removing support for Chrome Apps on Windows, Mac, and Linux. Chrome OS will continue to support Chrome Apps. Additionally, Chrome and the Web Store will continue to support extensions on all platforms. Read the announcement and learn more about migrating your app.

https://developer.chrome.com/apps/about_apps

Since support will be continued for Chrome OS I believe we can merge this.

**Comment by Links2004** [comment]
yes, the support in the Browser will be removed soon, only chrome OS will keep it.
and that´s the only place the APP needs to work.
It stated as extension but thanks to API limitations it now needs to be an APP.
since webpack-webextension build environment where in place already I adapted it to work for APP's too.

**Comment by tm1000** [comment]
All Apps are now being dropped: https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html

**Pull request closed without merging**
