### PR TITLE
mv3 manifest syntax support

### PR DESCRIPTION
**Pull request by here-nerd**
Please review the unit tests. I have not implemented the solution yet. I want to double check my understanding of the requirements.

### CODE REVIEW

**Comment by tm1000** [comment]
So I'm going to move forward with this and do it as as MINOR version release since you didn't need to break the API here (which I probably would have done). 

I still debate if we even want manifest validation because Chrome already enforces that, does this plugin need to enforce that too? It is something that'll need to be addressed in the future.

**Review by tm1000 — APPROVED** [review]

**Comment by here-nerd** [comment]
@tm1000 I share the same thought. That's why I didn't implement the actual MV3 validation, yet. Shall we remove the manifest validation entirely?

**Comment by tm1000** [comment]
I ended up having to do this as a major release only because the semantic versioning was still in I initial development (0.x.y). 

If you’d like to remove the manifest checking I think that would be a good idea. My quick overview of it was that it just checked background scripts and that’s it. 

For now you can at least use this from 1.0.0 for further work

**Comment by tm1000** [comment]
Ah nevermind it uses joi to validate the manifest pretty strictly. I like your setting for now that allows us to bypass the validation for things like supporting v3 that will at least allow development to continue

**Comment by here-nerd** [comment]
Then I propose creating another PR for:
- removing all mv3 manifest file validation.
- rename the validate-related functions to mv2ManifestValidate
- perform the validation only when the manifest is mv2.. skip otherwise.
What do you think?

**Comment by tm1000** [comment]
I think we can do a hybrid validation of the manifest where you can validate parts of v3 and v2. I did some work locally to test it and it worked. However I think it's still good to keep the skip validation parameter and that should be passed into the toolbox cli itself so people can just skip it. This way there is the best of both worlds. I think over time we could get rid of the validation all together it's just looking it over I dont want to do that.

As for you work you can just continue to use the skip validation I am fine with that I can work on the v3 and v2 combination and since we keep the skip validation it will work for more pro users like yourself

**Comment by here-nerd** [comment]
Ok, then for https://github.com/webextension-toolbox/webpack-webextension-plugin, i will park it as-is.

For the webextension-toolbox, there will be some more work to be done. I will continue on that.

**Pull request merged**
